### ISSUE TITLE
Grammar mistake

### ISSUE THREAD

**Issue by Cheffrey2000** [learn-co-curriculum/dsc-introduction-to-neural-networks#3]
If you are not talking about rain, sun, clouds, etc., this is the wrong 'weather'.  You should be using 'whether' which is a synonym for if.
![image](https://user-images.githubusercontent.com/52893814/72108347-60c92400-3301-11ea-8f96-9faad6120e9a.png)

**Comment by sumedh10** [comment]
Thanks, this is fixed.
