### ISSUE TITLE
Error thrown in Neural Network intro lesson

### ISSUE THREAD

**Issue by JM-Hansen** [learn-co-curriculum/dsc-introduction-to-neural-networks#6]
## Link to Canvas

https://learning.flatironschool.com/courses/5318/assignments/189535?module_item_id=422851

## Issue Subtype

- [ X] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
There is only one cell of code in this lesson
```

### Concern

TypeError: FigureBase.gca() got an unexpected keyword argument 'projection'

## What OS Are You Using?

- [ X] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
Thanks for opening this issue with us :wave:. The link to the Saturn Cloud notebook has been updated and opens to the correct notebook at this time.
