### ISSUE TITLE
Difficult to comprehend lesson

### ISSUE THREAD

**Issue by Davidkeebler** [learn-co-curriculum/dsc-introduction-to-neural-networks#7]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x ] Instructions unclear
- [ x] Other (explain below)

### Source

```

```

### Concern

This lesson is a wall of equations that are poorly explained and extremely difficult to follow. I am confident that nobody except for a PHD student would preexisting knowledge of the subject could follow its content or learn from it effectively.

## (Optional) Proposed Solution

Revise the lesson to better explain the symbols and terms used in the equations to make it easier to follow. As it stands, I cannot learn from or comprehend the content of this lesson, which is extremely concerning considering that it is very fundamental to how this technology works in the first place. I say this as a person who has extensively studied calculus and has preexisting knowledge of neural networks - this lesson is seriously in need of proofreading and revision to make it easier to follow and understand.

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for the input. We are always in the processing of revising and updating the curriculum in a cyclic manner to make it better. We've made a note of your suggestions for when we get to this content again.
